/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';
import { Role } from './role';


export interface User { 
    active?: boolean;
    encryptedPassword?: string;
    fullName?: string;
    id?: number;
    products?: Array<Product>;
    roles?: Array<Role>;
    username?: string;
}
